### ISSUE TITLE
CUDA load error on Windows 10

### ISSUE THREAD

**Issue by morgankohler** [BlinkDL/ChatRWKV#31]
Hey, this is great work. I have been trying to set this up from repo for windows and the biggest problem so far is this error in the cuda load step (ChatRWKV/rwkv_pip_package/src/rwkv/model.py:29):

"CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1."

I'm not too familiar with low-level cuda programs so having a tough time debugging. Maybe you have some idea? Thanks!

**Comment by BlinkDL** [comment]
Thank you :) Firstly set os.environ["RWKV_CUDA_ON"] = '0' and find your fastest strategy.

In order to use os.environ["RWKV_CUDA_ON"] = '1' in windows:

1. Install VS 2017 and Visual Studio Build Tools 2017.
2. Reinstall CUDA 11.7 (install VS extensions).
3. Run python chat.py in "x64 Native Tools Command Prompt for VS 2017" and it should be able to compile the CUDA kernel.

**Comment by morgankohler** [comment]
Great thanks. Will try this. Also, have you tried exporting to onnx?

**Comment by morgankohler** [comment]
Hey this fixed this issue for me but I am running out of memory on my GPU (3080 10gb VRAM). The weights I'm using are RWKV-4-Pile-14B-20230228-ctx4096-test663.pth from HuggingFace. I'm just following this portion of the setup:

`os.environ["RWKV_JIT_ON"] = '1'
os.environ["RWKV_CUDA_ON"] = '1'
from rwkv.model import RWKV
model = RWKV(model='.../RWKV-4-Pile-14B-20230228-ctx4096-test663.pth', strategy='cuda fp16')
`

On the readme it mentions only needing ~3gb for this model. Am I missing something?
